version: "3.7"
services:
  api:
    ports:
      - 8000:80
    env_file:
      - ../app/.dev.env
    volumes:
      - ../app/:/app/app/
    command: bash -c "while true; do sleep 1; done"

networks:
  default:
    external:
      name: $NETWORK_NAME
