version: "3.7"
services:
  api:
    image: "satellite_viewer:0.1.0"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: /start.sh

networks:
  default:
    external:
      name: $NETWORK_NAME